#!/bin/bash
# Example: direct post-quantum SSH connection using Falcon-1024.
#
# This script demonstrates how to connect to a post-quantum SSH server
# without going through the interactive wizard.  Adjust the variables
# below for your environment, then run:
#
#   bash docs/examples/connect_falcon1024.sh

# ── Configuration ─────────────────────────────────────────────────────────────
SERVER_HOST="192.168.1.10"    # IP or hostname of the post-quantum SSH server
SERVER_PORT="22"              # Port the post-quantum sshd is listening on
SERVER_USER="alice"           # Remote username
ALGORITHM="ssh-falcon1024"    # PQ algorithm (must match the server's host key)

# Path to the OQS ssh binary (built by build_oqs_openssh.sh)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SSH_BIN="${PROJECT_ROOT}/build/bin/ssh"

# Private key (generated by client/keygen.sh)
IDENTITY_FILE="${HOME}/.ssh/id_${ALGORITHM}"

# ── Pre-flight checks ─────────────────────────────────────────────────────────
if [[ ! -x "$SSH_BIN" ]]; then
    echo "ERROR: OQS ssh binary not found at ${SSH_BIN}" >&2
    echo "       Run: sudo bash build_oqs_openssh.sh" >&2
    exit 1
fi

if [[ ! -f "$IDENTITY_FILE" ]]; then
    echo "ERROR: Private key not found: ${IDENTITY_FILE}" >&2
    echo "       Run: bash client/keygen.sh" >&2
    exit 1
fi

# ── Connect ───────────────────────────────────────────────────────────────────
echo "Connecting to ${SERVER_USER}@${SERVER_HOST}:${SERVER_PORT} using ${ALGORITHM} ..."

# PQ KEX algorithms ensure the session key exchange is also quantum-resistant
KEX_ALGOS="ecdh-nistp384-kyber-1024r3-sha384-d00@openquantumsafe.org"
KEX_ALGOS="${KEX_ALGOS},ecdh-nistp256-kyber-512r3-sha256-d00@openquantumsafe.org"
KEX_ALGOS="${KEX_ALGOS},x25519-kyber-512r3-sha256-d00@openquantumsafe.org"

exec "${SSH_BIN}" \
    -o "KexAlgorithms=${KEX_ALGOS}" \
    -o "HostKeyAlgorithms=${ALGORITHM}" \
    -o "PubkeyAcceptedKeyTypes=${ALGORITHM}" \
    -i "${IDENTITY_FILE}" \
    -p "${SERVER_PORT}" \
    "${SERVER_USER}@${SERVER_HOST}"
