#!/bin/bash
set -eo pipefail

# PQ-Only Test Mode — experimental pure post-quantum SSH server.
#
# Sets up an sshd that accepts ONLY post-quantum algorithms (no classical
# fallback), on a dedicated port (default 2222).  Intended for test servers
# to prove PQ-only viability before production rollout.
#
# What this script does:
#   1. Generates PQ-only host keys (no Ed25519/RSA)
#   2. Writes sshd_config with PQ-only KEX + PQ-only auth
#   3. Configures firewall rules (ufw or iptables) for the PQ-only port
#   4. Creates a systemd service unit
#   5. Prints a test plan for CI/CD / GitHub deploy key verification
#
# WARNING: This mode is for test/staging servers only.  Classical SSH clients
# CANNOT connect to a PQ-only sshd.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../shared/config.sh"
source "${SCRIPT_DIR}/../shared/functions.sh"

INSTALL_DIR="${BUILD_DIR}"
PQ_ONLY_PORT="${PQ_ONLY_PORT:-2222}"
PQ_ONLY_SERVICE="evaemon-pqonly-sshd"
PQ_ONLY_SERVICE_FILE="/etc/systemd/system/${PQ_ONLY_SERVICE}.service"
PQ_ONLY_CONFIG="${CONFIG_DIR}/sshd_pq_only.config"
PQ_ONLY_PID="${BUILD_DIR}/var/run/sshd_pq_only.pid"

# ── Host key generation (PQ-only, no classical) ─────────────────────────────

setup_pq_only_keys() {
    local selected_algos=("$@")
    log_section "Generating PQ-Only Host Keys"

    for algo in "${selected_algos[@]}"; do
        local host_key="${KEY_DIR}/ssh_host_${algo}_key"
        if [[ ! -f "$host_key" ]]; then
            log_cmd "Generate host key (${algo})" \
                "${BIN_DIR}/ssh-keygen" -t "$algo" -f "$host_key" -N ""
            log_info "Host key created: ${host_key}"
        else
            log_info "Host key already exists: ${host_key}"
        fi
    done
}

# ── PQ-only sshd_config ─────────────────────────────────────────────────────

create_pq_only_config() {
    local port="$1"
    shift
    local algos=("$@")

    local algo_list
    algo_list="$(IFS=','; echo "${algos[*]}")"

    # PQ-only KEX: no classical fallback
    local pq_kex_list
    pq_kex_list="$(IFS=','; echo "${KEX_ALGORITHMS[*]}")"

    {
        echo "# PQ-Only Test Mode — generated by Evaemon pq_only_testmode.sh"
        echo "# WARNING: Classical SSH clients CANNOT connect to this server."
        echo ""
        echo "Port ${port}"
        for algo in "${algos[@]}"; do
            echo "HostKey ${KEY_DIR}/ssh_host_${algo}_key"
        done
        echo "HostKeyAlgorithms ${algo_list}"
        echo "PubkeyAcceptedKeyTypes ${algo_list}"
        echo "PubkeyAuthentication yes"
        echo "PasswordAuthentication no"
        echo "ChallengeResponseAuthentication no"
        echo "AuthenticationMethods publickey"
        echo "KexAlgorithms ${pq_kex_list}"
        echo "AuthorizedKeysFile .ssh/authorized_keys"
        echo "PermitRootLogin no"
        echo "StrictModes yes"
        echo "PidFile ${PQ_ONLY_PID}"
        echo "Subsystem sftp ${INSTALL_DIR}/libexec/sftp-server"
    } > "${PQ_ONLY_CONFIG}"

    log_info "Created PQ-only sshd_config: ${PQ_ONLY_CONFIG}"
    log_info "Algorithms: ${algo_list}"
    log_info "KEX: ${pq_kex_list}"
    log_warn "NO classical algorithms included — PQ-only mode."
}

# ── Firewall ─────────────────────────────────────────────────────────────────

configure_firewall() {
    local port="$1"
    local source_cidr="$2"

    log_section "Firewall Configuration for PQ-Only Port ${port}"

    if command -v ufw &>/dev/null; then
        log_info "Using ufw to configure firewall rules."

        if [[ -n "$source_cidr" ]]; then
            log_cmd "Allow PQ-only port from ${source_cidr}" \
                ufw allow from "${source_cidr}" to any port "${port}" proto tcp comment "Evaemon PQ-only SSH"
        else
            log_cmd "Allow PQ-only port" \
                ufw allow "${port}/tcp" comment "Evaemon PQ-only SSH"
        fi

        log_info "Firewall rules applied via ufw."
        ufw status verbose 2>/dev/null | grep -i "${port}" || true

    elif command -v iptables &>/dev/null; then
        log_info "Using iptables to configure firewall rules."

        if [[ -n "$source_cidr" ]]; then
            log_cmd "Allow PQ-only port from ${source_cidr}" \
                iptables -A INPUT -p tcp -s "${source_cidr}" --dport "${port}" -j ACCEPT \
                    -m comment --comment "Evaemon PQ-only SSH"
        else
            log_cmd "Allow PQ-only port" \
                iptables -A INPUT -p tcp --dport "${port}" -j ACCEPT \
                    -m comment --comment "Evaemon PQ-only SSH"
        fi

        log_info "Firewall rules applied via iptables."
    else
        log_warn "Neither ufw nor iptables found. Configure firewall manually:"
        log_warn "  Allow TCP port ${port} from trusted sources."
    fi
}

# ── Systemd service ──────────────────────────────────────────────────────────

create_pq_only_service() {
    cat > "${PQ_ONLY_SERVICE_FILE}" << EOF
[Unit]
Description=Post-Quantum SSH Server (PQ-Only Test Mode)
After=network.target

[Service]
Type=simple
ExecStart=${SBIN_DIR}/sshd -f ${PQ_ONLY_CONFIG} -D
Restart=on-failure
RestartSec=5s
StartLimitBurst=3
StartLimitIntervalSec=30s

[Install]
WantedBy=multi-user.target
EOF
    log_info "Created systemd service: ${PQ_ONLY_SERVICE_FILE}"

    log_cmd "systemctl daemon-reload" systemctl daemon-reload
    log_cmd "Enable ${PQ_ONLY_SERVICE}" systemctl enable "${PQ_ONLY_SERVICE}.service"
}

# ── Test plan ────────────────────────────────────────────────────────────────

print_test_plan() {
    local port="$1"
    local algo="$2"

    log_section "PQ-Only Test Plan"
    echo
    echo "1. Start the PQ-only sshd:"
    echo "     sudo systemctl start ${PQ_ONLY_SERVICE}.service"
    echo
    echo "2. Test with an Evaemon PQ client:"
    echo "     build/bin/ssh -o KexAlgorithms=${PQ_KEX_LIST} \\"
    echo "         -o HostKeyAlgorithms=${algo} \\"
    echo "         -o PubkeyAcceptedKeyTypes=${algo} \\"
    echo "         -i ~/.ssh/id_${algo} \\"
    echo "         -p ${port} user@this-server"
    echo
    echo "3. Verify classical clients are REJECTED:"
    echo "     ssh -p ${port} user@this-server"
    echo "     # Expected: connection refused or algorithm negotiation failure"
    echo
    echo "4. Test with GitHub deploy keys (CI/CD):"
    echo "     # In your CI pipeline, install OQS-OpenSSH and use:"
    echo "     EVAEMON_SERVER_HOST=this-server \\"
    echo "     EVAEMON_SERVER_PORT=${port} \\"
    echo "     EVAEMON_ALGORITHM=${algo} \\"
    echo "     bash docs/examples/automated_key_rotation.sh"
    echo
    echo "5. Monitor connections:"
    echo "     bash server/monitoring.sh"
    echo
    echo "6. Check logs:"
    echo "     journalctl -u ${PQ_ONLY_SERVICE}.service -f"
    echo
}

# ── Main ─────────────────────────────────────────────────────────────────────

main() {
    if [[ ! -x "${BIN_DIR}/ssh-keygen" ]]; then
        log_fatal "OQS-OpenSSH not found at ${BIN_DIR}/ssh-keygen. Please run the build first."
    fi

    log_section "PQ-Only Test Mode Setup"
    log_warn "This configures a PURE post-quantum SSH server."
    log_warn "Classical SSH clients will NOT be able to connect."
    echo

    # Port selection
    local port
    read -rp "PQ-only SSH port [${PQ_ONLY_PORT}]: " port
    port="${port:-${PQ_ONLY_PORT}}"
    validate_port "$port" || log_fatal "Invalid port number: ${port}"

    # Algorithm selection — recommend multi-family diversification
    log_section "Algorithm Selection (PQ-Only)"
    echo "For maximum resilience, select algorithms from DIFFERENT families:"
    echo "  - Lattice: Falcon-1024, ML-DSA-65"
    echo "  - Hash:    SPHINCS+-SHA2-256f, SLH-DSA-SHA2-256f"
    echo
    echo "1. Recommended multi-family set (Falcon-1024 + ML-DSA-65 + SPHINCS+-256f)"
    echo "2. Select specific algorithms"
    read -rp "Mode (1-2) [1]: " mode
    mode="${mode:-1}"

    local selected_algos=()
    case "$mode" in
        1)
            selected_algos=("ssh-falcon1024" "ssh-mldsa-65" "ssh-sphincssha2256fsimple")
            ;;
        2)
            list_algorithms
            read -rp "Enter algorithm numbers (space-separated): " -a choices
            for c in "${choices[@]}"; do
                validate_algorithm_choice "$c" "${#ALGORITHMS[@]}" || exit 1
                selected_algos+=("${ALGORITHMS[$((c-1))]}")
            done
            if [[ ${#selected_algos[@]} -eq 0 ]]; then
                log_fatal "No algorithms selected."
            fi
            ;;
        *)
            log_fatal "Invalid mode selection."
            ;;
    esac

    log_info "Selected ${#selected_algos[@]} PQ algorithm(s):"
    for a in "${selected_algos[@]}"; do
        log_info "  - ${a}"
    done

    # Source CIDR for firewall
    local source_cidr=""
    read -rp "Restrict to source CIDR (e.g. 10.0.0.0/8, leave empty for any): " source_cidr

    # Setup directories
    mkdir -p "${KEY_DIR}" "${CONFIG_DIR}" "${BUILD_DIR}/var/run"

    # Execute
    setup_pq_only_keys "${selected_algos[@]}"
    create_pq_only_config "$port" "${selected_algos[@]}"
    configure_firewall "$port" "$source_cidr"
    create_pq_only_service
    print_test_plan "$port" "${selected_algos[0]}"

    log_section "PQ-Only Test Mode Ready"
    log_info "Service: ${PQ_ONLY_SERVICE}"
    log_info "Config:  ${PQ_ONLY_CONFIG}"
    log_info "Port:    ${port}"
    log_success "Start with: sudo systemctl start ${PQ_ONLY_SERVICE}.service"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi
