#!/bin/bash
set -eo pipefail

# OTK-PQ Layer 1 — Post-Quantum Master Key Manager
#
# The master key is the root of trust in the OTK-PQ architecture.
# It never leaves the client and never touches the network after enrollment.
# Its sole purpose is to sign ephemeral session keys, proving they were
# generated by the legitimate client.
#
# Operations:
#   generate  — create a new ML-DSA-87 master key pair
#   verify    — check that the master key exists and is intact
#   export    — output the master public key for server enrollment
#   info      — display master key metadata (fingerprint, age, algorithm)
#   rotate    — generate a new master key and archive the old one

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../shared/otk_config.sh"
source "${SCRIPT_DIR}/../../shared/functions.sh"

# Determine the real (non-root) user for ownership.
if [[ -n "${SUDO_USER}" ]]; then
    REAL_USER="${SUDO_USER}"
else
    REAL_USER="$(whoami)"
fi

# ── Directory Setup ──────────────────────────────────────────────────────────

_ensure_otk_dirs() {
    if [[ ! -d "${OTK_MASTER_DIR}" ]]; then
        mkdir -p "${OTK_MASTER_DIR}"
        chmod "${OTK_DIR_PERMS}" "${OTK_MASTER_DIR}"
        # Ensure parent OTK directory also has correct permissions
        chmod "${OTK_DIR_PERMS}" "$(dirname "${OTK_MASTER_DIR}")"
        chown "${REAL_USER}:${REAL_USER}" "${OTK_MASTER_DIR}" 2>/dev/null || true
        chown "${REAL_USER}:${REAL_USER}" "$(dirname "${OTK_MASTER_DIR}")" 2>/dev/null || true
        log_debug "Created OTK master key directory: ${OTK_MASTER_DIR}"
    fi

    if [[ ! -d "${OTK_SESSION_DIR}" ]]; then
        mkdir -p "${OTK_SESSION_DIR}"
        chmod "${OTK_DIR_PERMS}" "${OTK_SESSION_DIR}"
        chown "${REAL_USER}:${REAL_USER}" "${OTK_SESSION_DIR}" 2>/dev/null || true
        log_debug "Created OTK session directory: ${OTK_SESSION_DIR}"
    fi
}

# ── Incomplete Key Detection ─────────────────────────────────────────────────

# _check_incomplete_keys
# Detect and warn about incomplete master key files left behind by interrupted
# key generation (e.g. ssh-keygen killed mid-operation).
# Returns 0 if no problems found, 1 if an incomplete or truncated key is detected.
_check_incomplete_keys() {
    local key_path="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_KEY}"
    local pub_path="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_PUB}"

    # Case 1: Private key exists but no public key
    if [[ -f "${key_path}" && ! -f "${pub_path}" ]]; then
        log_warn "Incomplete master key detected: private key exists but public key is missing"
        log_warn "This may be caused by an interrupted key generation"
        log_warn "Remove with: rm -f '${key_path}' and regenerate"
        return 1
    fi

    # Case 2: Public key exists but no private key
    if [[ ! -f "${key_path}" && -f "${pub_path}" ]]; then
        log_warn "Orphaned master public key detected: no matching private key"
        log_warn "Remove with: rm -f '${pub_path}' and regenerate"
        return 1
    fi

    # Case 3: Both exist — check if private key has reasonable size (not truncated)
    if [[ -f "${key_path}" ]]; then
        local key_size
        key_size="$(wc -c < "${key_path}" 2>/dev/null || echo 0)"
        if (( key_size < 100 )); then
            log_warn "Master private key appears truncated (${key_size} bytes)"
            log_warn "This may be caused by an interrupted key generation"
            return 1
        fi
    fi

    return 0
}

# ── Master Key Generation ────────────────────────────────────────────────────

# generate_master_key [--force]
# Generate a new ML-DSA-87 master key pair for OTK-PQ authentication.
# The private key stays on the client; the public key is enrolled on servers.
# Returns 0 on success, 1 if key already exists (without --force).
# Calls log_fatal (exits) if OQS build is missing or ssh-keygen fails.
generate_master_key() {
    local force=false
    [[ "${1:-}" == "--force" ]] && force=true

    _ensure_otk_dirs
    require_oqs_build

    local key_path="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_KEY}"
    local pub_path="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_PUB}"

    if [[ -f "${key_path}" ]] && ! $force; then
        log_warn "Master key already exists at ${key_path}."
        log_warn "Use --force to regenerate (this will require re-enrollment on all servers)."
        return 1
    fi

    if [[ -f "${key_path}" ]] && $force; then
        log_warn "Archiving existing master key before regeneration..."
        _archive_master_key
    fi

    log_section "OTK-PQ Layer 1 — Master Key Generation"
    log_info "Algorithm: ${OTK_MASTER_SIGN_ALGO} (ML-DSA-87, FIPS 204)"
    log_info "Security level: NIST Level 5"
    log_info "Purpose: Sign ephemeral session keys (never transmitted)"

    # Generate the ML-DSA-87 master signing key pair using OQS ssh-keygen.
    # No passphrase by default for automated session signing; users can
    # add one with ssh-keygen -p after generation.
    read -rp "Protect master key with a passphrase? (recommended) (y/N): " use_pass
    if [[ "${use_pass}" == "y" || "${use_pass}" == "Y" ]]; then
        log_cmd "Generate ML-DSA-87 master key (with passphrase)" \
            sudo -u "${REAL_USER}" "${BIN_DIR}/ssh-keygen" \
                -t "${OTK_MASTER_SIGN_ALGO}" \
                -f "${key_path}" \
                -C "otk-pq-master@$(hostname)-$(date +%Y%m%d)"
    else
        log_cmd "Generate ML-DSA-87 master key (no passphrase)" \
            sudo -u "${REAL_USER}" "${BIN_DIR}/ssh-keygen" \
                -t "${OTK_MASTER_SIGN_ALGO}" \
                -f "${key_path}" \
                -N "" \
                -C "otk-pq-master@$(hostname)-$(date +%Y%m%d)"
    fi

    # Set strict permissions.
    chmod "${OTK_PRIVATE_KEY_PERMS}" "${key_path}"
    chmod "${OTK_PUBLIC_KEY_PERMS}" "${pub_path}"
    chown "${REAL_USER}:${REAL_USER}" "${key_path}" "${pub_path}" 2>/dev/null || true

    # Record generation timestamp for age tracking.
    date +%s > "${OTK_MASTER_DIR}/.master_created"
    chmod "${OTK_PRIVATE_KEY_PERMS}" "${OTK_MASTER_DIR}/.master_created"

    log_success "Master key generated successfully."
    log_info "Private key: ${key_path}"
    log_info "Public key:  ${pub_path}"
    log_info ""
    log_info "Next step: Enroll the master public key on your server(s):"
    log_info "  bash client/otk/master_key.sh export | ssh user@server 'bash server/otk/otk_server.sh enroll'"
}

# ── Master Key Verification ─────────────────────────────────────────────────

# verify_master_key
# Check that the master key exists, has correct permissions, and is valid.
# Returns 0 if OK, 1 if problems found.
verify_master_key() {
    local key_path="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_KEY}"
    local pub_path="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_PUB}"
    local errors=0

    log_section "OTK-PQ Layer 1 — Master Key Verification"

    # Check for incomplete/corrupted keys from interrupted generation
    if ! _check_incomplete_keys; then
        (( errors++ )) || true
    fi

    # Check private key exists
    if [[ ! -f "${key_path}" ]]; then
        log_error "Master private key not found: ${key_path}"
        log_error "Generate one with: bash client/otk/master_key.sh generate"
        return 1
    fi
    log_success "Master private key exists: ${key_path}"

    # Check public key exists
    if [[ ! -f "${pub_path}" ]]; then
        log_error "Master public key not found: ${pub_path}"
        (( errors++ )) || true
    else
        log_success "Master public key exists: ${pub_path}"
    fi

    # Check permissions
    local priv_perms
    priv_perms="$(stat -c '%a' "${key_path}" 2>/dev/null || stat -f '%Lp' "${key_path}" 2>/dev/null)"
    if [[ "${priv_perms}" != "600" ]]; then
        log_warn "Master private key permissions are ${priv_perms} (expected 600)"
        (( errors++ )) || true
    else
        log_success "Master private key permissions OK (600)"
    fi

    # Check key age
    if [[ -f "${OTK_MASTER_DIR}/.master_created" ]]; then
        local created_ts current_ts age_days
        created_ts="$(cat "${OTK_MASTER_DIR}/.master_created")"
        current_ts="$(date +%s)"
        age_days="$(( (current_ts - created_ts) / 86400 ))"
        if (( age_days >= OTK_MASTER_MAX_AGE_DAYS )); then
            log_warn "Master key is ${age_days} days old (max recommended: ${OTK_MASTER_MAX_AGE_DAYS})"
            log_warn "Consider rotating with: bash client/otk/master_key.sh rotate"
        else
            log_success "Master key age: ${age_days} days (limit: ${OTK_MASTER_MAX_AGE_DAYS})"
        fi
    else
        log_warn "Master key creation timestamp not found — cannot check age"
    fi

    # Verify key fingerprint is readable
    if [[ -x "${BIN_DIR}/ssh-keygen" ]]; then
        local fingerprint
        fingerprint="$("${BIN_DIR}/ssh-keygen" -l -f "${pub_path}" 2>/dev/null || true)"
        if [[ -n "${fingerprint}" ]]; then
            log_success "Master key fingerprint: ${fingerprint}"
        else
            log_warn "Could not read master key fingerprint"
            (( errors++ )) || true
        fi
    fi

    if (( errors > 0 )); then
        log_warn "Verification completed with ${errors} warning(s)"
        return 1
    fi

    log_success "Master key verification passed"
    return 0
}

# ── Master Key Export ────────────────────────────────────────────────────────

# export_master_public_key
# Output the master public key contents to stdout for server enrollment.
# This is the ONLY time master key material should traverse the network —
# during initial enrollment over a trusted channel.
# Returns 0 on success; calls log_fatal (exits) if the public key is not found.
export_master_public_key() {
    local pub_path="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_PUB}"

    if [[ ! -f "${pub_path}" ]]; then
        log_fatal "Master public key not found: ${pub_path}. Generate one first."
    fi

    cat "${pub_path}"
}

# ── Master Key Info ──────────────────────────────────────────────────────────

# master_key_info
# Display metadata about the master key (fingerprint, algorithm, age).
# Returns 0 on success, 1 if no master key is found.
master_key_info() {
    local key_path="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_KEY}"
    local pub_path="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_PUB}"

    log_section "OTK-PQ Master Key Information"

    if [[ ! -f "${key_path}" ]]; then
        log_error "No master key found. Generate one with: bash client/otk/master_key.sh generate"
        return 1
    fi

    log_info "Algorithm:    ${OTK_MASTER_SIGN_ALGO} (ML-DSA-87)"
    log_info "Standard:     NIST FIPS 204"
    log_info "Security:     Level 5"
    log_info "Private key:  ${key_path}"
    log_info "Public key:   ${pub_path}"

    if [[ -x "${BIN_DIR}/ssh-keygen" ]] && [[ -f "${pub_path}" ]]; then
        local fingerprint
        fingerprint="$("${BIN_DIR}/ssh-keygen" -l -f "${pub_path}" 2>/dev/null || true)"
        [[ -n "${fingerprint}" ]] && log_info "Fingerprint:  ${fingerprint}"
    fi

    if [[ -f "${OTK_MASTER_DIR}/.master_created" ]]; then
        local created_ts age_days created_date
        created_ts="$(cat "${OTK_MASTER_DIR}/.master_created")"
        age_days="$(( ($(date +%s) - created_ts) / 86400 ))"
        created_date="$(date -d "@${created_ts}" "+%Y-%m-%d %H:%M:%S" 2>/dev/null || date -r "${created_ts}" "+%Y-%m-%d %H:%M:%S" 2>/dev/null || echo "unknown")"
        log_info "Created:      ${created_date}"
        log_info "Age:          ${age_days} days (max: ${OTK_MASTER_MAX_AGE_DAYS})"
    fi

    local key_size
    key_size="$(wc -c < "${key_path}" 2>/dev/null || echo "unknown")"
    log_info "Key size:     ${key_size} bytes"
}

# ── Master Key Rotation ─────────────────────────────────────────────────────

# _archive_master_key
# Move the current master key to an archive directory with timestamp.
# Returns 0 always.
_archive_master_key() {
    local archive_dir="${OTK_MASTER_DIR}/archive"
    local timestamp
    timestamp="$(date +%Y%m%d_%H%M%S)"
    local archive_path="${archive_dir}/${timestamp}"

    mkdir -p "${archive_path}"
    chmod "${OTK_DIR_PERMS}" "${archive_dir}" "${archive_path}"

    local key_path="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_KEY}"
    local pub_path="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_PUB}"

    [[ -f "${key_path}" ]] && mv "${key_path}" "${archive_path}/"
    [[ -f "${pub_path}" ]] && mv "${pub_path}" "${archive_path}/"
    [[ -f "${OTK_MASTER_DIR}/.master_created" ]] && mv "${OTK_MASTER_DIR}/.master_created" "${archive_path}/"

    log_info "Archived master key to: ${archive_path}"
}

# rotate_master_key
# Generate a new master key and archive the old one.
# WARNING: After rotation, all servers must re-enroll the new public key.
# Returns 0 on success or cancellation.
rotate_master_key() {
    log_section "OTK-PQ Master Key Rotation"
    log_warn "IMPORTANT: After rotation, all servers must re-enroll your new master public key."
    log_warn "Sessions signed with the old master key will be rejected."
    echo
    read -rp "Proceed with master key rotation? (y/N): " confirm
    if [[ "${confirm}" != "y" && "${confirm}" != "Y" ]]; then
        log_info "Rotation cancelled."
        return 0
    fi

    generate_master_key --force
    log_success "Master key rotated. Remember to re-enroll on all servers."
}

# ── Main ─────────────────────────────────────────────────────────────────────

main() {
    local command="${1:-}"

    case "${command}" in
        generate)
            shift
            generate_master_key "$@"
            ;;
        verify)
            verify_master_key
            ;;
        export)
            export_master_public_key
            ;;
        info)
            master_key_info
            ;;
        rotate)
            rotate_master_key
            ;;
        *)
            echo "OTK-PQ Layer 1 — Master Key Manager"
            echo "──────────────────────────────────────"
            echo
            echo "Usage: $(basename "$0") <command>"
            echo
            echo "Commands:"
            echo "  generate [--force]  Generate a new ML-DSA-87 master key pair"
            echo "  verify              Check master key integrity and permissions"
            echo "  export              Output master public key for server enrollment"
            echo "  info                Display master key metadata"
            echo "  rotate              Generate new master key (archives old one)"
            echo
            echo "The master key is the root of trust — it never leaves this device"
            echo "and never touches the network after initial enrollment."
            return 1
            ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
