#!/bin/bash
set -eo pipefail

# OTK-PQ Layer 2 — Hybrid Session Key Engine
#
# Generates a fresh hybrid key pair for every session:
#   - Classical component: Ed25519 (signing)
#   - Post-quantum component: ML-DSA-87 signed ephemeral key
#   - Both are ephemeral — generated per session, destroyed after use
#
# The session key is signed by the master key (Layer 1) to prove it was
# generated by the legitimate client.  The server verifies this signature
# against the enrolled master public key before accepting the session.
#
# A session bundle is produced containing:
#   session_key/session_key.pub  — ephemeral Ed25519 key pair
#   session_pq_key/pub           — ephemeral PQ key pair (for hybrid auth)
#   master_signature             — ML-DSA-87 signature over session public keys
#   nonce                        — timestamp + random for replay prevention
#   session_id                   — unique identifier (hash of nonce + pubkeys)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../shared/otk_config.sh"
source "${SCRIPT_DIR}/../../shared/functions.sh"

# ── Nonce Generation ────────────────────────────────────────────────────────

# generate_nonce OUTPUT_DIR
# Create a session nonce: timestamp (epoch seconds) + cryptographic random.
# Written to OUTPUT_DIR/nonce as "TIMESTAMP:RANDOM_HEX".
# Prints the nonce to stdout. Returns 0 on success; exits non-zero if openssl fails.
generate_nonce() {
    local output_dir="$1"
    local timestamp random_hex nonce

    timestamp="$(date +%s)"
    random_hex="$(openssl rand -hex "${OTK_NONCE_RANDOM_BYTES}")"
    nonce="${timestamp}:${random_hex}"

    printf '%s' "${nonce}" > "${output_dir}/nonce"
    chmod "${OTK_PRIVATE_KEY_PERMS}" "${output_dir}/nonce"

    log_debug "Generated nonce: timestamp=${timestamp}, random=${OTK_NONCE_RANDOM_BYTES} bytes"
    echo "${nonce}"
}

# validate_nonce NONCE
# Check that a nonce is well-formed and within the acceptable time window.
# Returns 0 if valid, 1 if expired or malformed.
validate_nonce() {
    local nonce="$1"

    # Parse timestamp:random format
    local timestamp random_hex
    timestamp="${nonce%%:*}"
    random_hex="${nonce#*:}"

    if [[ -z "${timestamp}" || -z "${random_hex}" || "${timestamp}" == "${nonce}" ]]; then
        log_error "Malformed nonce: missing timestamp or random component"
        return 1
    fi

    if [[ ! "${timestamp}" =~ ^[0-9]+$ ]]; then
        log_error "Malformed nonce: timestamp is not a number"
        return 1
    fi

    # Check age
    local current_ts age
    current_ts="$(date +%s)"
    age=$(( current_ts - timestamp ))

    if (( age < 0 )); then
        log_error "Nonce timestamp is in the future (clock skew: ${age}s)"
        return 1
    fi

    if (( age > OTK_NONCE_MAX_AGE )); then
        log_error "Nonce expired: ${age}s old (max: ${OTK_NONCE_MAX_AGE}s)"
        return 1
    fi

    log_debug "Nonce valid: age=${age}s (max: ${OTK_NONCE_MAX_AGE}s)"
    return 0
}

# ── Session ID Generation ────────────────────────────────────────────────────

# generate_session_id NONCE SESSION_PUB_KEY_PATH [PQ_PUB_KEY_PATH]
# Compute a unique session ID by hashing the nonce + public key material.
# Uses SHA3-256 (FIPS 202) for the revocation ledger; falls back to SHA-256.
# Prints the hex session ID to stdout. Returns 0 on success.
generate_session_id() {
    local nonce="$1"
    local session_pub="$2"
    local pq_pub="${3:-}"
    local hash_input session_id

    # Concatenate nonce + session public key(s) for the hash input
    hash_input="${nonce}"
    hash_input+="$(cat "${session_pub}")"
    [[ -n "${pq_pub}" && -f "${pq_pub}" ]] && hash_input+="$(cat "${pq_pub}")"

    # Use SHA3-256 if available, fallback to SHA-256
    if openssl dgst -sha3-256 /dev/null &>/dev/null; then
        session_id="$(printf '%s' "${hash_input}" | openssl dgst -sha3-256 -hex 2>/dev/null | awk '{print $NF}')"
    else
        log_debug "SHA3-256 not available in OpenSSL, using SHA-256 fallback"
        session_id="$(printf '%s' "${hash_input}" | openssl dgst -sha256 -hex 2>/dev/null | awk '{print $NF}')"
    fi

    echo "${session_id}"
}

# ── Session Key Generation ───────────────────────────────────────────────────

# generate_session_keypair
# Create a fresh ephemeral hybrid key pair for a single session.
# Prints the path to the session bundle directory to stdout.
# Returns 0 on success; calls log_fatal (exits) if master key is missing or keygen fails.
generate_session_keypair() {
    require_oqs_build

    # Verify master key exists (required to sign session keys)
    local master_key="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_KEY}"
    local master_pub="${OTK_MASTER_DIR}/${OTK_MASTER_SIGN_PUB}"
    if [[ ! -f "${master_key}" ]]; then
        log_fatal "Master key not found at ${master_key}. Run: bash client/otk/master_key.sh generate"
    fi

    # Create a unique session bundle directory
    local bundle_id bundle_dir
    bundle_id="$(date +%s%N)_$(openssl rand -hex 8)"
    bundle_dir="${OTK_SESSION_DIR}/${bundle_id}"
    mkdir -p "${bundle_dir}"
    chmod "${OTK_DIR_PERMS}" "${bundle_dir}"

    log_debug "Creating session bundle: ${bundle_dir}"

    # ── Classical component: Ed25519 ephemeral key ──
    log_debug "Generating ephemeral Ed25519 session key..."
    "${BIN_DIR}/ssh-keygen" \
        -t "${OTK_SESSION_CLASSICAL_SIGN}" \
        -f "${bundle_dir}/session_key" \
        -N "" \
        -C "otk-session-$(date +%s)" \
        -q

    chmod "${OTK_PRIVATE_KEY_PERMS}" "${bundle_dir}/session_key"
    chmod "${OTK_PUBLIC_KEY_PERMS}" "${bundle_dir}/session_key.pub"

    # ── Post-quantum component: PQ ephemeral key ──
    # Use the first recommended PQ algorithm for session authentication
    local pq_algo="${OTK_MASTER_SIGN_ALGO}"
    log_debug "Generating ephemeral PQ session key (${pq_algo})..."
    "${BIN_DIR}/ssh-keygen" \
        -t "${pq_algo}" \
        -f "${bundle_dir}/session_pq_key" \
        -N "" \
        -C "otk-session-pq-$(date +%s)" \
        -q

    chmod "${OTK_PRIVATE_KEY_PERMS}" "${bundle_dir}/session_pq_key"
    chmod "${OTK_PUBLIC_KEY_PERMS}" "${bundle_dir}/session_pq_key.pub"

    # ── Generate nonce ──
    local nonce
    nonce="$(generate_nonce "${bundle_dir}")"

    # ── Generate session ID ──
    local session_id
    session_id="$(generate_session_id "${nonce}" "${bundle_dir}/session_key.pub" "${bundle_dir}/session_pq_key.pub")"
    printf '%s' "${session_id}" > "${bundle_dir}/session_id"
    chmod "${OTK_PRIVATE_KEY_PERMS}" "${bundle_dir}/session_id"

    # ── Sign session public keys with master key (Layer 1 → Layer 2 binding) ──
    sign_session_keys "${bundle_dir}" "${master_key}"

    log_debug "Session bundle created: ${bundle_dir}"
    log_debug "Session ID: ${session_id}"

    echo "${bundle_dir}"
}

# ── Session Key Signing ─────────────────────────────────────────────────────

# sign_session_keys BUNDLE_DIR MASTER_PRIVATE_KEY
# Create a signature over the session public keys + nonce using the master key.
# This binds the ephemeral session to the master identity (Layer 1 → Layer 2).
# Returns 0 on success; calls log_fatal (exits) if signing fails.
sign_session_keys() {
    local bundle_dir="$1"
    local master_key="$2"

    # Build the message to sign: nonce + classical pub + PQ pub
    local sign_data="${bundle_dir}/.sign_data"
    {
        cat "${bundle_dir}/nonce"
        cat "${bundle_dir}/session_key.pub"
        cat "${bundle_dir}/session_pq_key.pub"
    } > "${sign_data}"

    # Sign using ssh-keygen -Y sign (available in OpenSSH 8.0+)
    # This creates a detached signature using the master key.
    "${BIN_DIR}/ssh-keygen" \
        -Y sign \
        -f "${master_key}" \
        -n "otk-session" \
        "${sign_data}" 2>/dev/null

    # ssh-keygen -Y sign creates <file>.sig
    if [[ -f "${sign_data}.sig" ]]; then
        mv "${sign_data}.sig" "${bundle_dir}/master_signature"
        chmod "${OTK_PRIVATE_KEY_PERMS}" "${bundle_dir}/master_signature"
        log_debug "Session keys signed with master key"
    else
        # Cleanup on failure
        rm -rf "${bundle_dir}"
        log_fatal "Failed to sign session keys with master key"
    fi

    # Remove temporary sign data
    rm -f "${sign_data}"
}

# ── Session Bundle Export ────────────────────────────────────────────────────

# export_session_bundle BUNDLE_DIR
# Package the session bundle for transmission to the server.
# Copies: session public keys + master signature + nonce + session ID.
# Private keys are NEVER exported.
# Prints the export directory path to stdout.
# Returns 0 on success; calls log_fatal (exits) if bundle directory is missing.
export_session_bundle() {
    local bundle_dir="$1"

    if [[ ! -d "${bundle_dir}" ]]; then
        log_fatal "Session bundle not found: ${bundle_dir}"
    fi

    # Create a transmission package (public material only)
    local export_dir="${bundle_dir}/export"
    mkdir -p "${export_dir}"

    cp "${bundle_dir}/session_key.pub" "${export_dir}/"
    cp "${bundle_dir}/session_pq_key.pub" "${export_dir}/"
    cp "${bundle_dir}/master_signature" "${export_dir}/"
    cp "${bundle_dir}/nonce" "${export_dir}/"
    cp "${bundle_dir}/session_id" "${export_dir}/"

    echo "${export_dir}"
}

# ── Session Bundle Listing ───────────────────────────────────────────────────

# list_active_sessions
# Show any active (not yet destroyed) session bundles.
# Returns 0 always (no active sessions is normal and expected).
list_active_sessions() {
    log_section "Active OTK Session Bundles"

    if [[ ! -d "${OTK_SESSION_DIR}" ]]; then
        log_info "No session directory found."
        return 0
    fi

    local count=0
    for bundle_dir in "${OTK_SESSION_DIR}"/*/; do
        [[ -d "${bundle_dir}" ]] || continue
        local session_id="unknown"
        [[ -f "${bundle_dir}/session_id" ]] && session_id="$(cat "${bundle_dir}/session_id")"
        local bundle_name
        bundle_name="$(basename "${bundle_dir}")"
        log_info "  ${bundle_name} — session_id: ${session_id:0:16}..."
        (( count++ )) || true
    done

    if (( count == 0 )); then
        log_info "No active sessions. (This is expected — sessions are destroyed after use.)"
    else
        log_warn "${count} active session(s) found. These should be destroyed after use."
    fi
}

# ── Main ─────────────────────────────────────────────────────────────────────

main() {
    local command="${1:-}"

    case "${command}" in
        generate)
            local bundle_dir
            bundle_dir="$(generate_session_keypair)"
            log_success "Session bundle created: ${bundle_dir}"
            ;;
        list)
            list_active_sessions
            ;;
        *)
            echo "OTK-PQ Layer 2 — Session Key Engine"
            echo "──────────────────────────────────────"
            echo
            echo "Usage: $(basename "$0") <command>"
            echo
            echo "Commands:"
            echo "  generate  Generate a fresh hybrid session key pair"
            echo "  list      Show active (undestroyed) session bundles"
            echo
            echo "Session keys are ephemeral — generated per session and"
            echo "signed by the master key to prove legitimacy."
            return 1
            ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
